parameters:
#    coteaux_chasse_site.example.class: CoteauxChasse\SiteBundle\Example

services:
#    coteaux_chasse_site.example:
#        class: %coteaux_chasse_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
