coteaux_chasse_actus_homepage:
    path:     /actus
    defaults: { _controller: CoteauxChasseActusBundle:Default:index }

coteaux_chasse_actus_create:
    path:     /admin/actus/create 
    defaults: { _controller: CoteauxChasseActusBundle:Default:create }