homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:index }

actus_homepage:
    path:     /actus
    defaults: { _controller: AppBundle:Actu:index }

actus_create:
    path:     /admin/actus/create
    defaults: { _controller: AppBundle:Actu:create }

documents:
    path: /documents
    defaults: { _controller: AppBundle:Document:index }
    
document_dl:
    path: /document/{docId}
    defaults: { _controller: AppBundle:Document:downloadFile }
    requirements:
      id: \d+
    
documents_add:
    path: /documents/add
    defaults: { _controller: AppBundle:Document:add }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
