coteaux_chasse_actus:
    resource: "@CoteauxChasseActusBundle/Resources/config/routing.yml"
    prefix:   /

coteaux_chasse_site:
    resource: "@CoteauxChasseSiteBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"