homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

contact:
    path: /contact
    defaults: { _controller: AppBundle:Contact:index }

actus_homepage:
    path:     /actus
    defaults: { _controller: AppBundle:Actu:index }

actus_create:
    path:     /admin/actus/create
    defaults: { _controller: AppBundle:Actu:create }

actus_modif:
    path:     /admin/actus/modif/{actuId}
    defaults: { _controller: AppBundle:Actu:modifActu }
    requirements:
      id: \d+
      
actus_delete:
    path: /admin/actus/delete/{actuId}
    defaults: { _controller: AppBundle:Actu:deleteActu }
    requirements:
      id: \d+


documents:
    path: /documents
    defaults: { _controller: AppBundle:Document:index }
    
document_dl:
    path: /document/{docId}
    defaults: { _controller: AppBundle:Document:downloadFile }
    requirements:
      id: \d+
      
document_delete:
    path: /admin/document/{docId}
    defaults: { _controller: AppBundle:Document:delete }
    requirements:
      id: \d+
    
documents_add:
    path: /admin/documents/add
    defaults: { _controller: AppBundle:Document:add }
    
plus_infos_homepage:
    path:     /plusInfos
    defaults: { _controller: AppBundle:Default:plusInfos }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
